frontend:InstallDeps:
  image: node:14-alpine3.13
  stage: install
  script:
    - cd frontend
    # node_modules exists => cache with key nodemodule+yarn.lock hash exists => node_modules up to date with yarn.lock
    - test -d node_modules/ && { echo "Skipping $CI_JOB_NAME, node_modules already up-to-date."; exit 207; }
    - cp yarn.lock yarn.lock.orig
    - yarn install --cache-folder .yarn --prefer-offline
    # this check is necessary because --frozen-lockfile is buggy: yarn.lock will be updated if a "resolution" requires it
    - cmp -s yarn.lock yarn.lock.orig || { echo "yarn.lock file is not up-to-date, please run a yarn install locally"; exit 1; }
  allow_failure:
    exit_codes: 207
  cache:
    - key: yarncache-$CI_JOB_IMAGE
      paths:
        - frontend/.yarn
    - key:
        prefix: nodemodules-$CI_JOB_IMAGE
        files:
          - frontend/yarn.lock
      paths:
        - frontend/node_modules

frontend:Tests:
  image: node:14-alpine3.13
  rules:
    - if: "$CI_MERGE_REQUEST_IID"
  stage: test
  before_script:
    - cd frontend
    - test -d node_modules/ || yarn install --frozen-lockfile
  script:
    - yarn lint --cache --cache-strategy content --cache-location .cicache/eslint/.cache.json
    - yarn test:coverage --cacheDirectory .cicache/jest
  cache:
    - key:
        prefix: nodemodules-$CI_JOB_IMAGE
        files:
          - frontend/yarn.lock
      paths:
        - frontend/node_modules
      policy: pull
    - key:
        prefix: cicache-$CI_JOB_IMAGE
        files:
          - frontend/yarn.lock
      paths:
        - frontend/.cicache
  needs: ["frontend:InstallDeps"]

frontend:Build:
  image: node:14-alpine3.13
  stage: build
  before_script:
    - cd frontend
    - test -d  node_modules/ || yarn install --frozen-lockfile
  script:
    - yarn build
  cache:
    - key:
        prefix: nodemodules-$CI_JOB_IMAGE
        files:
          - frontend/yarn.lock
      paths:
        - frontend/node_modules
      policy: pull
    - key: buildcache-$CI_COMMIT_BRANCH-$CI_JOB_IMAGE
      paths:
        - frontend/.next/cache
  needs: ["frontend:Tests"]
