api:tests:
  image: openjdk:17-jdk-alpine
  stage: test
  script:
    - cd backend/api
    - ./mvnw $MAVEN_CLI_OPTS clean verify
    #   Report coverage to GitLab's MR overview
    - awk -F"," '{ instructions += $4 + $5; instructionsCovered += $5;
      branches += $6 + $7; branchesCovered += $7;
      lines += $8 + $9; linesCovered += $9;
      conditions += $10 + $11; conditionsCovered += $11;
      methods += $12 + $13; methodsCovered += $13 }
      END { print "Instructions coverage :", 100*instructionsCovered/instructions;
      print "Branches coverage :", 100*branchesCovered/branches;
      print "Lines coverage :", 100*linesCovered/lines;
      print "Cyclomatic complexity coverage :", 100*conditionsCovered/conditions;
      print "Methods coverage :", 100*methodsCovered/methods;
      print "Average code coverage:", 100*(instructionsCovered/instructions + branchesCovered/branches + linesCovered/lines + conditionsCovered/conditions + methodsCovered/methods)/5 }'
      target/site/jacoco/jacoco.csv
  coverage: '/Average code coverage: \d+\.\d+/'
  cache:
    paths:
      - backend/.m2/repository
  needs: []

  artifacts:
    reports:
      junit:
        - backend/api/target/surefire-reports/TEST-*.xml
    paths:
      - backend/api/target/site/jacoco/jacoco.xml

# taken from https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html#java-and-kotlin-examples
api:report-coverage:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py backend/api/target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/backend/api/src/main/java/ > backend/api/target/site/cobertura.xml
  needs: ["api:tests"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/api/target/site/cobertura.xml

  cache: {}

api:owasp_dependency_check:
  image:
    name: owasp/dependency-check
    entrypoint: [""]
  stage: test
  needs: []
  script:
    - whoami
    - cd backend/api
    - git config --global --add safe.directory /builds/nimbleways/internal/jidokabot/jidokabot
    - git fetch origin main
    - git show "$(git log -n 1 origin/main --pretty=format:"%H")":backend/api/pom.xml > mainPom.xml
    - git diff --no-index -U0 mainPom.xml pom.xml> diffPom.txt  || echo "do not exit"
    - if [ -s diffPom.txt ];
      then ./mvnw $MAVEN_CLI_OPTS -B dependency:list  -Dsort=true -DoutputFile="dependency.txt" -DoutputAbsoluteArtifactFilename;
      ./mvnw $MAVEN_CLI_OPTS -f mainPom.xml -B dependency:list  -Dsort=true -DoutputFile="dependencyMain.txt" -DoutputAbsoluteArtifactFilename;
      git diff --no-index -U0 dependencyMain.txt dependency.txt > diff.txt  || echo "do not exit" ;
      if [ -s diff.txt ]; then
      grep ^+  diff.txt | grep -Eo "(C:|/builds)/[a-zA-Z0-9./\?=_%:-]*" | while read line; do echo " -s "$line >> scanOpts.txt ; done ;
      if [ -s scanOpts.txt ];
      then SCAN_OPTS="$(cat scanOpts.txt | tr -d '\n')";
      echo -e "\e[34m The new dependencies :$SCAN_OPTS" ;
      /usr/share/dependency-check/bin/dependency-check.sh $SCAN_OPTS
      --format JSON --format HTML --prettyPrint  --failOnCVSS 8 --data $CI_PROJECT_DIR/backend/.m2/repository/org/owasp/dependency-check-data/script/ --disableAssembly --disableNugetconf
      --disableNuspec --disableRetireJS ;
      if [ $(grep -c "vulnerabilities" dependency-check-report.json) -gt 0 ]; then echo -e "\033[31m The new added dependencies are vulnerable, check the report for more info"; exit 2;
      else echo -e  "\e[34mNo vulnerabilities found"; fi;
      else echo -e "\033[31mError in scan oprions" ; fi
      else echo -e "\e[34mNo new dependencies found" ; fi
      else echo -e "\e[34mNo difference between poms files"; fi
  cache:
    # this duplicated cache is needed because this image runs with a different user than the others, causing permission problems
    key: dep-check-cache
    paths:
      - backend/.m2/repository
  artifacts:
    when: on_failure
    paths:
      # Save the HTML and JSON report artifacts
      - "backend/api/dependency-check-report.html"
