version: "3.1"

services:
  db:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: